global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['localhost:9999']
        labels:
          service: 'kafka-broker'

  - job_name: 'kafka-connect'
    static_configs:
      - targets: ['localhost:9998']
        labels:
          service: 'kafka-connect'

  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:9187']
        labels:
          service: 'postgresql'

  # Add prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']