---
lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
  # Kafka Connect metrics
  - pattern: kafka.connect<type=connect-worker-metrics, client-id=(.+)><>([a-z-]+)
    name: kafka_connect_worker_$2
    type: GAUGE
    labels:
      client_id: "$1"
  - pattern: kafka.connect<type=connect-metrics, client-id=(.+)><>([a-z-]+)
    name: kafka_connect_$2
    type: GAUGE
    labels:
      client_id: "$1"
  - pattern: kafka.connect<type=connector-task-metrics, connector=(.+), task=(.+)><>([a-z-]+)
    name: kafka_connect_connector_task_$3
    type: GAUGE
    labels:
      connector: "$1"
      task: "$2"
  - pattern: kafka.connect<type=connector-metrics, connector=(.+)><>([a-z-]+)
    name: kafka_connect_connector_$2
    type: GAUGE
    labels:
      connector: "$1"
  - pattern: kafka.connect<type=sink-task-metrics, connector=(.+), task=(.+)><>([a-z-]+)
    name: kafka_connect_sink_task_$3
    type: GAUGE
    labels:
      connector: "$1"
      task: "$2"
  - pattern: kafka.connect<type=source-task-metrics, connector=(.+), task=(.+)><>([a-z-]+)
    name: kafka_connect_source_task_$3
    type: GAUGE
    labels:
      connector: "$1"
      task: "$2"
  - pattern: debezium.([^:]+)<type=connector-metrics, context=([^,]+), server=([^,]+), key=([^>]+)><>([^:]+)
    name: debezium_$1_$2_$5
    type: GAUGE
    labels:
      server: "$3"
      key: "$4"
# Added below for Standalone Debezium Connector metrics
  - pattern: 'io.debezium.connector.postgresql:type=connector-metrics,context=source,server=([^,]+)><>([^:]+)'
    name: 'debezium_pg_connector_$2'
    labels:
      server: "$1"
    type: GAUGE
  - pattern: 'io.debezium.connector.postgresql:type=source-task-metrics,context=source,server=([^,]+),task=([0-9]+)><>([^:]+)'
    name: 'debezium_pg_task_$3'
    labels:
      server: "$1"
      task: "$2"
    type: GAUGE
# Truied to add based on MBean information from JConsole 
  - pattern: "debezium.([^:]+)<type=connector-metrics, context=([^,]+), server=([^,]+), key=([^>]+)><>RowsScanned"
    name: "debezium_metrics_RowsScanned"
    labels:
      plugin: "$1"
      name: "$3"
      context: "$2"
      table: "$4"
  - pattern: "debezium.([^:]+)<type=connector-metrics, server=([^,]+), task=([^,]+), context=([^,]+), database=([^>]+)>([^:]+)"
    name: "debezium_metrics_$6"
    labels:
      plugin: "$1"
      name: "$2"
      task: "$3"
      context: "$4"
      database: "$5"
  - pattern: "debezium.([^:]+)<type=connector-metrics, server=([^,]+), task=([^,]+), context=([^>]+)>([^:]+)"
    name: "debezium_metrics_$5"
    labels:
      plugin: "$1"
      name: "$2"
      task: "$3"
      context: "$4"
  - pattern: "debezium.([^:]+)<type=connector-metrics, context=([^,]+), server=([^>]+)>([^:]+)"
    name: "debezium_metrics_$4"
    labels:
      plugin: "$1"
      name: "$3"
      context: "$2"
#Some more rules
  - pattern: 'kafka.connect<type=connector-metrics, connector=([^,]+),.*><>([^:]+)'
    name: 'connect_connector_$2'
    labels:
      connector: "$1"
    type: GAUGE

  - pattern: 'kafka.connect<type=task-metrics, connector=([^,]+), task=([0-9]+)><>([^:]+)'
    name: 'connect_task_$3'
    labels:
      connector: "$1"
      task: "$2"
    type: GAUGE

  - pattern: 'kafka.connect<type=source-task-metrics, connector=([^,]+), task=([0-9]+)><>([^:]+)'
    name: 'connect_source_task_$3'
    labels:
      connector: "$1"
      task: "$2"
    type: GAUGE

  - pattern: 'kafka.connect<type=connector-task-metrics, connector=([^,]+), task=([0-9]+)><>([^:]+)'
    name: 'connect_connector_task_$3'
    labels:
      connector: "$1"
      task: "$2"
    type: GAUGE

  - pattern: 'debezium\.metrics:type=connector-metrics,context=source,server=(.*),name=(.*)><>([^:]+)'
    name: 'debezium_connector_$3'
    labels:
      server: "$1"
      name: "$2"
    type: GAUGE
