{
 "title": "Debezium Connector Events",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "connector_type",
    "label": "Connector Type",
    "query": "debezium_metrics_TotalNumberOfEventsSeen"
   },
   {
    "name": "connector_name",
    "label": "Connector Name",
    "query": "debezium_metrics_TotalNumberOfEventsSeen{plugin=\"$connector_type\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Streaming",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time since last event",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_millisecondssincelastevent{}"
      }
     ]
    },
    {
     "title": "Event count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 3, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "debezium_metrics_totalnumberofeventsseen{}",
       "legendFormat": "Total events received"
      },
      {
       "expr": "debezium_metrics_NumberOfEventsSkipped{plugin=\"$connector_type\",name=\"$connector_name\",context=~\"(binlog|streaming)\"}",
       "legendFormat": "Events skipped"
      }
     ]
    },
    {
     "title": "Connected",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "debezium_metrics_connected{}" }
     ]
    }
   ]
  },
  {
   "title": "Snapshot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table count",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_totaltablecount{}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Remaining tables",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_remainingtablecount{}",
       "legendFormat": "Remaining"
      }
     ]
    },
    {
     "title": "Snapshot Running",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_snapshotrunning{}"
      }
     ]
    },
    {
     "title": "Completed",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_snapshotcompleted{}"
      }
     ]
    },
    {
     "title": "Aborted",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_snapshotaborted{}"
      }
     ]
    },
    {
     "title": "Event count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "debezium_metrics_totalnumberofeventsseen{}",
       "legendFormat": "Total events received"
      },
      {
       "expr": "debezium_metrics_numberoferroneousevents{}",
       "legendFormat": "Events skipped"
      }
     ]
    },
    {
     "title": "Rows scanned",
     "type": "table",
     "gridPos": { "h": 6, "w": 5, "x": 6, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "debezium_metrics_RowsScanned{plugin=\"$connector_type\",name=\"$connector_name\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Debezium Connector Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Number of Events",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "debezium_metrics_totalnumberofeventsseen{}",
       "legendFormat": "Incoming({{client}})"
      }
     ]
    },
    {
     "title": "Total No. of Create Events",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "debezium_metrics_totalnumberofcreateeventsseen{}",
       "legendFormat": "Incoming({{client}})"
      }
     ]
    },
    {
     "title": "Total No. of Update Events",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "debezium_metrics_totalnumberofupdateeventsseen{}",
       "legendFormat": "Incoming({{client}})"
      }
     ]
    },
    {
     "title": "Total No. of Delete Events",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "debezium_metrics_totalnumberofdeleteeventsseen{}",
       "legendFormat": "Incoming({{client}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Connect",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network - Incoming vs Outgoing Byte Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_connect_incoming_byte_rate{}",
       "legendFormat": "Incoming({{client}})"
      },
      {
       "expr": "kafka_connect_outgoing_byte_rate{}",
       "legendFormat": "Outgoing({{client}})"
      }
     ]
    }
   ]
  },
  { "title": "Kafka Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Topic Department",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PostgreSQL ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{area='heap'}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_bytes_max{area='heap'}",
       "legendFormat": "Maximum"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "jvm_threads_current", "legendFormat": "Running" },
      { "expr": "jvm_threads_peak", "legendFormat": "Maximum" },
      { "expr": "jvm_threads_started_total", "legendFormat": "Started in total" }
     ]
    }
   ]
  }
 ]
}